- name: Home
  href: /

- name: API Documentation
  href: api/

- name: Source Repository
  href: https://github.com/PlayEveryWare/eos_plugin_for_unity
  
- name: UPM Packages
  href: https://github.com/PlayEveryWare/eos_plugin_for_unity_upm

- name: Support Issues
  href: https://github.com/PlayEveryWare/eos_plugin_for_unity/issues
